### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by abhieshekumar** [iiitkottayam/betaLABS#1]
The web page is not completely responsive.

![Image 1](https://user-images.githubusercontent.com/24494390/54919599-38fe0080-4f27-11e9-9292-89dc687a17c3.png)

![Image 2](https://user-images.githubusercontent.com/24494390/54919606-3c918780-4f27-11e9-9f86-78442d88c622.png)

**Comment by chensokheng123** [comment]
Hi, Can I work on this one?

**Comment by daemonsloth** [comment]
umm...somebody else is already working on it, we forgot to assign them.

**Comment by chensokheng123** [comment]
Alright, thank for the information.

**Comment by abhieshekumar** [comment]
#8
